DROP TABLE KALIMA;
CREATE TABLE KALIMA ( 
	KALIMA_ID INTEGER,
	SECTION_ID INTEGER,
	KALIMA_ISM_S VARCHAR(255),
	KALIMA_ISM_P VARCHAR(255),
	KALIMA_FIL_MA VARCHAR(255),
	KALIMA_FIL_MU VARCHAR(255),
	KALIMA_MASDAR VARCHAR(255),
	KALIMA_HARF VARCHAR(255),
	KALIMA_MEANING VARCHAR(255),
	KALIMA_EXAMPLE VARCHAR(255),
	KALIMA_SORT_KALIMA BIGINT,
	KALIMA_SORT_JIDHR BIGINT,
	KALIMA_JIDHR1 VARCHAR(255),
	KALIMA_JIDHR2 VARCHAR(255),
	KALIMA_JIDHR3 VARCHAR(255),
	KALIMA_JIDHR4 VARCHAR(255),
	KALIMA_JIDHR5 VARCHAR(255),
	KALIMA_LAYOUT_SEQ INTEGER
);


CREATE TABLE SECTION (
	SECTION_ID INTEGER,
	SECTION_NAME VARCHAR(255)
);

INSERT INTO SECTION (SECTION_ID, SECTION_NAME) VALUES (1,'Kitchen Appliances');

INSERT INTO KALIMA (KALIMA_ID, KALIMA_ISM_S, KALIMA_ISM_P,KALIMA_FIL_MA,
	KALIMA_FIL_MU,
	KALIMA_MASDAR,
	KALIMA_HARF,
	KALIMA_MEANING,
	KALIMA_EXAMPLE,
	KALIMA_SORT_KALIMA,
	KALIMA_JIDHR1,
	KALIMA_JIDHR2,
	KALIMA_JIDHR3,
	KALIMA_JIDHR4,
	KALIMA_JIDHR5
) VALUES(1,'kitaab','kutub','','','','','','','','','','','','');

SELECT * FROM KALIMA;
