
from data.unicode_data import *

WORD_TYPE_NOUN = 1
WORD_TYPE_VERB = 2
WORD_TYPE_PREPOSITION = 3
WORD_TYPE_CONJUNCTION = 4
WORD_TYPE_INTERROGATIVE = 5
WORD_TYPE_NAME = 6

WORD_TENSE_PAST = 1
WORD_TENSE_PRESENT = 2

WORD_NUMBER_SINGULAR = 1
WORD_NUMBER_DUAL = 2
WORD_NUMBER_PLURAL = 3

WORD_GENDER_FEMININE = 1
WORD_GENDER_MASCULINE = 2
WORD_GENDER_EITHER = 3

WORD_CASE_MARFUUC = 1
WORD_CASE_MANSUUB = 2
WORD_CASE_MAJRUUR = 3

WORD_MOOD_MARFUUC = 1
WORD_MOOD_MANSUUB = 2
WORD_MOOD_MAJZUUM = 3

TU = TAA + DAMMA
TA = TAA + FATHA
TI = TAA + KASRA
NA = NUUN + FATHA
UU = WAAW + ALIF
NAA = NUUN + ALIF
TUM =  TAA + DAMMA + MIIM
TUMAA = TAA + DAMMA + MIIM + FATHA + ALIF
AT = FATHA + TAA + SUKUUN
AL = ALIF + LAAM

A = ALIF + FATHA
YA = YAA + FATHA
NA = NUUN + FATHA
IINA = YAA + NUUN + FATHA
UUNA = WAAW + NUUN + FATHA
AANI = ALIF + NUUN + KASRA
