

from data.unicode_data import *

HTML_TRANSLITERATIONS = {}
HTML_TRANSLITERATIONS_REVERSE = {}

HTML_TRANSLITERATIONS[ALIF] = 'Alif'
HTML_TRANSLITERATIONS[BAA] = 'Ba'
HTML_TRANSLITERATIONS[TAA] = 'Ta'
HTML_TRANSLITERATIONS[THAA] = 'Tha'
HTML_TRANSLITERATIONS[JIIM] = 'Jiim'
HTML_TRANSLITERATIONS[HAA_] = 'Ha'
HTML_TRANSLITERATIONS[KHAA] = 'Kha'
HTML_TRANSLITERATIONS[DAAL] = 'Dal'
HTML_TRANSLITERATIONS[DHAAL] = 'Thal'
HTML_TRANSLITERATIONS[RAA] = 'Ra'
HTML_TRANSLITERATIONS[ZAAL] = 'Zay'
HTML_TRANSLITERATIONS[SIIN] = 'Siin'
HTML_TRANSLITERATIONS[SHIIN] = 'Sh'
HTML_TRANSLITERATIONS[SAAD] = 'Sad'
HTML_TRANSLITERATIONS[DAAD] = 'Dad'
HTML_TRANSLITERATIONS[TAA_] = 'Tay'
HTML_TRANSLITERATIONS[DHAA_] = 'Za'
HTML_TRANSLITERATIONS[AYN] = 'Ayn'
HTML_TRANSLITERATIONS[GHAYN] = 'Gh'
HTML_TRANSLITERATIONS[FAA] = 'Fa'
HTML_TRANSLITERATIONS[QAAF] = 'Qaf'
HTML_TRANSLITERATIONS[KAAF] = 'Kaf'
HTML_TRANSLITERATIONS[LAAM] = 'Lam'
HTML_TRANSLITERATIONS[MIIM] = 'Miim'
HTML_TRANSLITERATIONS[NUUN] = 'Nun'
HTML_TRANSLITERATIONS[HAA] = 'ha'
HTML_TRANSLITERATIONS[WAAW] = 'Waw'
HTML_TRANSLITERATIONS[YAA] = 'Ya'
#HTML_TRANSLITERATIONS[HAMZA] = 'ALIF'

for unicode_char in HTML_TRANSLITERATIONS:
    HTML_TRANSLITERATIONS_REVERSE[HTML_TRANSLITERATIONS[unicode_char]] = unicode_char
    
HTML_TRANSLITERATIONS_REVERSE['Nuun'] = NUUN
HTML_TRANSLITERATIONS_REVERSE['Kh'] = KHAA
HTML_TRANSLITERATIONS_REVERSE['Daad'] = DAAD
HTML_TRANSLITERATIONS_REVERSE['Meem'] = MIIM
HTML_TRANSLITERATIONS_REVERSE['Mim'] = MIIM
HTML_TRANSLITERATIONS_REVERSE['Sin'] = SIIN
HTML_TRANSLITERATIONS_REVERSE['Shin'] = SHIIN
HTML_TRANSLITERATIONS_REVERSE['Saad'] = SAAD
HTML_TRANSLITERATIONS_REVERSE['Jim'] =  JIIM
HTML_TRANSLITERATIONS_REVERSE['Kaaf'] =  KAAF
HTML_TRANSLITERATIONS_REVERSE['Haa'] =  HAA_
    

