
from data.unicode_data import *

# no harakaat
KALB = KAAF + LAAM + BAA
FAKATABA = FAA + KAAF + TAA + BAA
KTB = KAAF + TAA + BAA
KITAAB = KAAF + TAA + ALIF + BAA
KITAABA = KAAF + TAA + ALIF + BAA + TAA_MARBUTA
KUTUB = KAAF + DAMMA + TAA + DAMMA + BAA
ALKUTUB = ALIF + LAAM + KUTUB
ALKITAAB = ALIF + LAAM + KAAF + TAA + ALIF + BAA
KITAABAAN = KAAF + TAA + ALIF + BAA + ALIF + NUUN
KITAABAYN = KAAF + TAA + ALIF + BAA + YAA + NUUN

KAATIB = KAAF + ALIF + TAA + KASRA + BAA

KATABA = KAAF + TAA + BAA
AKTUBU = HAMZA + KAAF + TAA + BAA
YAKTUB = YAA + KAAF + TAA + BAA
YAKTUBU = YAA + KAAF + TAA + BAA + DAMMA
TAKTUBU = TAA + KAAF + TAA + BAA + SUKUUN
TAKTUBU = TAA + KAAF + TAA + BAA + DAMMA
NAKTUBU = NUUN + KAAF + TAA + BAA
YAKTUBUUNA = YAA + KAAF + TAA + BAA + WAAW + NUUN
TAKTUBUUNA = TAA + KAAF + TAA + BAA + WAAW + NUUN

UKTUB = ALIF + KAAF + TAA + BAA
UKTUBUU = ALIF + KAAF + TAA + BAA + WAAW + ALIF

# with harakaat
KITAAB_ = KAAF + KASRA + TAA  + ALIF + BAA
KATABA_ = KAAF + FATHA + TAA + FATHA + BAA + FATHA
KATABAT_ = KAAF + FATHA + TAA + FATHA + BAA + FATHA + TAA

# composite words
BILKITAAB = BAA + ALIF + LAAM + KITAAB
LILKITAAB = LAAM + LAAM + KITAAB
BIKITAABIHI = BAA + KITAAB + HAA
BIKITAABIHI_ = BAA + KASRA + KITAAB_ + HAA + KASRA
KUTUBUHAA = KUTUB + HAA
LILKUTUB = LAAM + LAAM + KUTUB
KUTUBUHUM = KUTUB + HAA + MIIM
KUTUBUKA = KUTUB + KAAF
KUTUBUKI = KUTUB + KAAF
KUTUBUKUM = KUTUB + KAAF + MIIM
KITAABUHU = KITAAB + HAA
KITAABII = KITAAB + YAA
KITAABUHAA = KITAAB + HAA + ALIF
KITAABATUHU = KITAAB + TAA + HAA

SAYAKTUB = SIIN + YAA + KAAF + TAA + BAA

############

KHAALIQ = KHAA + ALIF + LAAM + QAAF

############

WLD = WAAW + LAAM + DAAL

############

WHD = WAAW + HAA_ + DAAL
AHAD = HAMZA_1 + HAA_ + DAAL
AHAD_ = HAMZA_1 + FATHA + HAA_ + DAAL + DAMMATAAN

############

FCL = FAA + AYN + LAAM 
FACALA = FAA + AYN + LAAM 

############

SMC = SIIN + MIIM + AYN
SAMICA = SIIN + MIIM + AYN

############

BSHR = BAA + SHIIN + RAA
BASHSHARA = BAA + SHIIN + SHADDA + RAA
BASHSHIR = BAA + SHIIN + SHADDA + RAA
BASHSHIRUU = BAA + SHIIN + SHADDA + RAA + WAAW + ALIF
TBSHSHRUU = TAA + BASHSHIRUU
TUBASHSHIRUU = TAA + DAMMA + BAA + FATHA + SHIIN + SHADDA + KASRA + RAA + WAAW + ALIF
YUBASHSHIRU = YAA + BAA + SHIIN + SHADDA + RAA

############

FII = FAA + KASRA + YAA
MACA = MIIM + FATHA + AYN + FATHA

############

DIIN = DAAL + YAA + NUUN
DIIN2 = DAAL + KASRA + YAA + NUUN
ADDIIN = ALIF + LAAM + DAAL + SHADDA + YAA + NUUN
ADDIIN2 = ALIF + LAAM + DAAL + SHADDA + KASRA + YAA + NUUN

############

MUSLIM = MIIM + SIIN + LAAM + MIIM
MUSLIMA = MIIM + SIIN + LAAM + MIIM + TAA_MARBUTA
MUSLIMAAT = MIIM + SIIN + LAAM + MIIM + ALIF + TAA
ISLAM = HAMZA + SIIN + LAAM + ALIF + MIIM
ISLAMIYA = ISLAM + YAA + SHADDA + TAA_MARBUTA
ISLAMIYA2 = ISLAM + YAA + TAA_MARBUTA

############

RAJUL = RAA + JIIM + LAAM
RAJULAN = RAA + JIIM + LAAM + ALIF + FATHATAAN
RAJULAN2 = RAA + JIIM + LAAM + ALIF

